### ISSUE TITLE
some quesions about the dataset

### ISSUE THREAD

**Issue by liuyeah** [qjzhzw/Open_QG#1]
我发现您给出的数据集是经过处理过后的数据集，想请问你说的 “原始数据由Song et al., 2018提供” 具体是那篇文章？

**Comment by qjzhzw** [comment]
> 我发现您给出的数据集是经过处理过后的数据集，想请问你说的 “原始数据由Song et al., 2018提供” 具体是那篇文章？

《Leveraging Context Information for Natural Question Generation》
这是他那篇文章的github地址：https://github.com/freesunshine0316/MPQG

**Comment by liuyeah** [comment]
因为我最近也在做qg方向，也是准备用transformer去做。可我看到您使用transformer训练后的效果与传统的LSTM的效果有不小的差距，请问您有考虑过什么原因么？（理论上来说，transformer能比LSTM、GRU更容易抓取序列的时序信息，在nlp的多数task上的表现也都优于传统的seq2seq架构）

**Comment by liuyeah** [comment]
> > 我发现您给出的数据集是经过处理过后的数据集，想请问你说的 “原始数据由Song et al., 2018提供” 具体是那篇文章？
> 
> 《Leveraging Context Information for Natural Question Generation》
> 这是他那篇文章的github地址：https://github.com/freesunshine0316/MPQG
