### ISSUE TITLE
结果疑问

### ISSUE THREAD

**Issue by liuyeah** [qjzhzw/Open_QG#2]
因为我最近也在做qg方向，也是准备用transformer去做。可我看到您使用transformer训练后的效果与传统的LSTM的效果有不小的差距，请问您有考虑过什么原因么？（理论上来说，transformer能比LSTM、GRU更容易抓取序列的时序信息，在nlp的多数task上的表现也都优于传统的seq2seq架构）

**Comment by qjzhzw** [comment]
我说一下我的看法：

1.我本身的代码实现这块，我是按照transformer原论文实现的，实现过程中有参考台大学生复现的一个项目和fairseq的相关代码，然后也调过参。大体上保证代码没有问题，但是不知道细节上是不是有什么值得改进的地方(毕竟就是自己写的)。

2.transformer最早是在机器翻译上提出来的，实验证明transformer在机器翻译上也确实取得了非常好的效果。但是在其它领域比如问题生成、文本摘要领域中，大部分还是用的基于LSTM的模型架构。可能有人做过一些相关尝试但是效果不好。

3.问题生成和机器翻译在任务性质上有所不同，具体来说有这几点：
(1)问题生成的输入序列往往比输出序列长很多。
(2)机器翻译的输入输出间是有对齐关系的(单词之间的翻译其实是一种映射关系)，而问题生成没有这种关系。
(3)问题生成很依赖于copy机制(当然我已经加入了copy机制但是感觉提升并不明显)。

我也是做QG的，如果你想继续交流，欢迎加我QQ450388261
