### ISSUE TITLE
有一个小疑问

### ISSUE THREAD

**Issue by weikang-wang** [qjzhzw/Open_QG#3]
请问为什么在保存最佳模型的时候是选择保存损失最小的模型，而不是保存bleu值最大的模型。

**Comment by qjzhzw** [comment]
因为验证阶段采取的是和训练阶段相同的策略，将真实输出右移一位作为decoder的输入，也就是预测每个输出词时是已知前面所有真实词的（teacher forcing），因此计算BLEU没有意义。
