### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by qinshuaibo** [qjzhzw/Open_QG#6]
你好，我想问一下，在Linux系统下执行sh文件，怎么没反应呢

**Comment by qjzhzw** [comment]
> 你好，我想问一下，在Linux系统下执行sh文件，怎么没反应呢

你好，执行 sh XXX.sh 或者 ./XXX.sh 都可以，如果是输入参数有问题的话会有提示的（可以看pipeline.sh里的代码）
